# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CadastroUsuario.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CadastroUsuario.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\025ObjectCadastroUsuario'),
  serialized_pb=_b('\n\x15\x43\x61\x64\x61stroUsuario.proto\x12\x05proto\"n\n\x0f\x43\x61\x64\x61stroUsuario\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0f\n\x07usuario\x18\x02 \x01(\t\x12\r\n\x05senha\x18\x03 \x01(\t\x12\x0b\n\x03\x63pf\x18\x04 \x01(\t\x12\x11\n\tmatricula\x18\x05 \x01(\t\x12\r\n\x05\x63urso\x18\x06 \x01(\tB-\n\x14sd.ufc.reserva.modelB\x15ObjectCadastroUsuariob\x06proto3')
)




_CADASTROUSUARIO = _descriptor.Descriptor(
  name='CadastroUsuario',
  full_name='proto.CadastroUsuario',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nome', full_name='proto.CadastroUsuario.nome', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='usuario', full_name='proto.CadastroUsuario.usuario', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='senha', full_name='proto.CadastroUsuario.senha', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpf', full_name='proto.CadastroUsuario.cpf', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matricula', full_name='proto.CadastroUsuario.matricula', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='curso', full_name='proto.CadastroUsuario.curso', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['CadastroUsuario'] = _CADASTROUSUARIO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CadastroUsuario = _reflection.GeneratedProtocolMessageType('CadastroUsuario', (_message.Message,), {
  'DESCRIPTOR' : _CADASTROUSUARIO,
  '__module__' : 'CadastroUsuario_pb2'
  # @@protoc_insertion_point(class_scope:proto.CadastroUsuario)
  })
_sym_db.RegisterMessage(CadastroUsuario)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
