# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Identificacao.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Identificacao.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\023ObjectIdentificacao'),
  serialized_pb=_b('\n\x13Identificacao.proto\x12\x05proto\"\x1b\n\rIdentificacao\x12\n\n\x02id\x18\x01 \x01(\x05\x42+\n\x14sd.ufc.reserva.modelB\x13ObjectIdentificacaob\x06proto3')
)




_IDENTIFICACAO = _descriptor.Descriptor(
  name='Identificacao',
  full_name='proto.Identificacao',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Identificacao.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['Identificacao'] = _IDENTIFICACAO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Identificacao = _reflection.GeneratedProtocolMessageType('Identificacao', (_message.Message,), {
  'DESCRIPTOR' : _IDENTIFICACAO,
  '__module__' : 'Identificacao_pb2'
  # @@protoc_insertion_point(class_scope:proto.Identificacao)
  })
_sym_db.RegisterMessage(Identificacao)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
