# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ListaSala.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model.Sala_pb2 as Sala__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ListaSala.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\017ObjectListaSala'),
  serialized_pb=_b('\n\x0fListaSala.proto\x12\x05proto\x1a\nSala.proto\"&\n\tListaSala\x12\x19\n\x04list\x18\x01 \x03(\x0b\x32\x0b.proto.SalaB\'\n\x14sd.ufc.reserva.modelB\x0fObjectListaSalab\x06proto3')
  ,
  dependencies=[Sala__pb2.DESCRIPTOR,])




_LISTASALA = _descriptor.Descriptor(
  name='ListaSala',
  full_name='proto.ListaSala',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='list', full_name='proto.ListaSala.list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=76,
)

_LISTASALA.fields_by_name['list'].message_type = Sala__pb2._SALA
DESCRIPTOR.message_types_by_name['ListaSala'] = _LISTASALA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListaSala = _reflection.GeneratedProtocolMessageType('ListaSala', (_message.Message,), {
  'DESCRIPTOR' : _LISTASALA,
  '__module__' : 'ListaSala_pb2'
  # @@protoc_insertion_point(class_scope:proto.ListaSala)
  })
_sym_db.RegisterMessage(ListaSala)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
