# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ListaReserva.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import model.Reserva_pb2 as Reserva__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ListaReserva.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\022ObjectListaReserva'),
  serialized_pb=_b('\n\x12ListaReserva.proto\x12\x05proto\x1a\rReserva.proto\"0\n\x0cListaReserva\x12 \n\x08reservas\x18\x01 \x03(\x0b\x32\x0e.proto.ReservaB*\n\x14sd.ufc.reserva.modelB\x12ObjectListaReservab\x06proto3')
  ,
  dependencies=[Reserva__pb2.DESCRIPTOR,])




_LISTARESERVA = _descriptor.Descriptor(
  name='ListaReserva',
  full_name='proto.ListaReserva',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reservas', full_name='proto.ListaReserva.reservas', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=92,
)

_LISTARESERVA.fields_by_name['reservas'].message_type = Reserva__pb2._RESERVA
DESCRIPTOR.message_types_by_name['ListaReserva'] = _LISTARESERVA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ListaReserva = _reflection.GeneratedProtocolMessageType('ListaReserva', (_message.Message,), {
  'DESCRIPTOR' : _LISTARESERVA,
  '__module__' : 'ListaReserva_pb2'
  # @@protoc_insertion_point(class_scope:proto.ListaReserva)
  })
_sym_db.RegisterMessage(ListaReserva)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
