# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Mensagem.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Mensagem.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\016ObjectMensagem'),
  serialized_pb=_b('\n\x0eMensagem.proto\x12\x05proto\"p\n\x08Mensagem\x12\x13\n\x0bmessageType\x18\x01 \x01(\x05\x12\x12\n\nrequest_id\x18\x02 \x01(\x05\x12\x18\n\x10object_reference\x18\x03 \x01(\t\x12\x0e\n\x06method\x18\x04 \x01(\t\x12\x11\n\targuments\x18\x05 \x01(\x0c\x42&\n\x14sd.ufc.reserva.modelB\x0eObjectMensagemb\x06proto3')
)




_MENSAGEM = _descriptor.Descriptor(
  name='Mensagem',
  full_name='proto.Mensagem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='messageType', full_name='proto.Mensagem.messageType', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='proto.Mensagem.request_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='object_reference', full_name='proto.Mensagem.object_reference', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='method', full_name='proto.Mensagem.method', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='arguments', full_name='proto.Mensagem.arguments', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['Mensagem'] = _MENSAGEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Mensagem = _reflection.GeneratedProtocolMessageType('Mensagem', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGEM,
  '__module__' : 'Mensagem_pb2'
  # @@protoc_insertion_point(class_scope:proto.Mensagem)
  })
_sym_db.RegisterMessage(Mensagem)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
