# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageCallback.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageCallback.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\025ObjectMessageCallback'),
  serialized_pb=_b('\n\x15MessageCallback.proto\x12\x05proto\"#\n\x0fMessageCallback\x12\x10\n\x08mensagem\x18\x01 \x01(\tB-\n\x14sd.ufc.reserva.modelB\x15ObjectMessageCallbackb\x06proto3')
)




_MESSAGECALLBACK = _descriptor.Descriptor(
  name='MessageCallback',
  full_name='proto.MessageCallback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='mensagem', full_name='proto.MessageCallback.mensagem', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)

DESCRIPTOR.message_types_by_name['MessageCallback'] = _MESSAGECALLBACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageCallback = _reflection.GeneratedProtocolMessageType('MessageCallback', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGECALLBACK,
  '__module__' : 'MessageCallback_pb2'
  # @@protoc_insertion_point(class_scope:proto.MessageCallback)
  })
_sym_db.RegisterMessage(MessageCallback)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
