# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Reserva.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Reserva.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\rObjectReserva'),
  serialized_pb=_b('\n\rReserva.proto\x12\x05proto\"Y\n\x07Reserva\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nid_usuario\x18\x02 \x01(\x05\x12\x0f\n\x07id_sala\x18\x03 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\x12\x0f\n\x07horario\x18\x05 \x01(\tB%\n\x14sd.ufc.reserva.modelB\rObjectReservab\x06proto3')
)




_RESERVA = _descriptor.Descriptor(
  name='Reserva',
  full_name='proto.Reserva',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Reserva.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_usuario', full_name='proto.Reserva.id_usuario', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_sala', full_name='proto.Reserva.id_sala', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='proto.Reserva.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='horario', full_name='proto.Reserva.horario', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=113,
)

DESCRIPTOR.message_types_by_name['Reserva'] = _RESERVA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Reserva = _reflection.GeneratedProtocolMessageType('Reserva', (_message.Message,), {
  'DESCRIPTOR' : _RESERVA,
  '__module__' : 'Reserva_pb2'
  # @@protoc_insertion_point(class_scope:proto.Reserva)
  })
_sym_db.RegisterMessage(Reserva)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
