# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Sala.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Sala.proto',
  package='proto',
  syntax='proto3',
  serialized_options=_b('\n\024sd.ufc.reserva.modelB\nObjectSala'),
  serialized_pb=_b('\n\nSala.proto\x12\x05proto\"4\n\x04Sala\x12\x0f\n\x07id_sala\x18\x01 \x01(\x05\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05\x62loco\x18\x03 \x01(\tB\"\n\x14sd.ufc.reserva.modelB\nObjectSalab\x06proto3')
)




_SALA = _descriptor.Descriptor(
  name='Sala',
  full_name='proto.Sala',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id_sala', full_name='proto.Sala.id_sala', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nome', full_name='proto.Sala.nome', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bloco', full_name='proto.Sala.bloco', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Sala'] = _SALA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sala = _reflection.GeneratedProtocolMessageType('Sala', (_message.Message,), {
  'DESCRIPTOR' : _SALA,
  '__module__' : 'Sala_pb2'
  # @@protoc_insertion_point(class_scope:proto.Sala)
  })
_sym_db.RegisterMessage(Sala)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
