// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/CadastroUsuario.proto

package sd.ufc.reserva.model;

public final class ObjectCadastroUsuario {
  private ObjectCadastroUsuario() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CadastroUsuarioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.CadastroUsuario)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    com.google.protobuf.ByteString
        getNomeBytes();

    /**
     * <code>string usuario = 2;</code>
     * @return The usuario.
     */
    java.lang.String getUsuario();
    /**
     * <code>string usuario = 2;</code>
     * @return The bytes for usuario.
     */
    com.google.protobuf.ByteString
        getUsuarioBytes();

    /**
     * <code>string senha = 3;</code>
     * @return The senha.
     */
    java.lang.String getSenha();
    /**
     * <code>string senha = 3;</code>
     * @return The bytes for senha.
     */
    com.google.protobuf.ByteString
        getSenhaBytes();

    /**
     * <code>string cpf = 4;</code>
     * @return The cpf.
     */
    java.lang.String getCpf();
    /**
     * <code>string cpf = 4;</code>
     * @return The bytes for cpf.
     */
    com.google.protobuf.ByteString
        getCpfBytes();

    /**
     * <code>string matricula = 5;</code>
     * @return The matricula.
     */
    java.lang.String getMatricula();
    /**
     * <code>string matricula = 5;</code>
     * @return The bytes for matricula.
     */
    com.google.protobuf.ByteString
        getMatriculaBytes();

    /**
     * <code>string curso = 6;</code>
     * @return The curso.
     */
    java.lang.String getCurso();
    /**
     * <code>string curso = 6;</code>
     * @return The bytes for curso.
     */
    com.google.protobuf.ByteString
        getCursoBytes();
  }
  /**
   * Protobuf type {@code proto.CadastroUsuario}
   */
  public  static final class CadastroUsuario extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.CadastroUsuario)
      CadastroUsuarioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CadastroUsuario.newBuilder() to construct.
    private CadastroUsuario(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CadastroUsuario() {
      nome_ = "";
      usuario_ = "";
      senha_ = "";
      cpf_ = "";
      matricula_ = "";
      curso_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new CadastroUsuario();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CadastroUsuario(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              usuario_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              senha_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              cpf_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              matricula_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              curso_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sd.ufc.reserva.model.ObjectCadastroUsuario.internal_static_proto_CadastroUsuario_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sd.ufc.reserva.model.ObjectCadastroUsuario.internal_static_proto_CadastroUsuario_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.class, sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.Builder.class);
    }

    public static final int NOME_FIELD_NUMBER = 1;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 1;</code>
     * @return The nome.
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 1;</code>
     * @return The bytes for nome.
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USUARIO_FIELD_NUMBER = 2;
    private volatile java.lang.Object usuario_;
    /**
     * <code>string usuario = 2;</code>
     * @return The usuario.
     */
    public java.lang.String getUsuario() {
      java.lang.Object ref = usuario_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        usuario_ = s;
        return s;
      }
    }
    /**
     * <code>string usuario = 2;</code>
     * @return The bytes for usuario.
     */
    public com.google.protobuf.ByteString
        getUsuarioBytes() {
      java.lang.Object ref = usuario_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        usuario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SENHA_FIELD_NUMBER = 3;
    private volatile java.lang.Object senha_;
    /**
     * <code>string senha = 3;</code>
     * @return The senha.
     */
    public java.lang.String getSenha() {
      java.lang.Object ref = senha_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        senha_ = s;
        return s;
      }
    }
    /**
     * <code>string senha = 3;</code>
     * @return The bytes for senha.
     */
    public com.google.protobuf.ByteString
        getSenhaBytes() {
      java.lang.Object ref = senha_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senha_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPF_FIELD_NUMBER = 4;
    private volatile java.lang.Object cpf_;
    /**
     * <code>string cpf = 4;</code>
     * @return The cpf.
     */
    public java.lang.String getCpf() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpf_ = s;
        return s;
      }
    }
    /**
     * <code>string cpf = 4;</code>
     * @return The bytes for cpf.
     */
    public com.google.protobuf.ByteString
        getCpfBytes() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MATRICULA_FIELD_NUMBER = 5;
    private volatile java.lang.Object matricula_;
    /**
     * <code>string matricula = 5;</code>
     * @return The matricula.
     */
    public java.lang.String getMatricula() {
      java.lang.Object ref = matricula_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        matricula_ = s;
        return s;
      }
    }
    /**
     * <code>string matricula = 5;</code>
     * @return The bytes for matricula.
     */
    public com.google.protobuf.ByteString
        getMatriculaBytes() {
      java.lang.Object ref = matricula_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        matricula_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURSO_FIELD_NUMBER = 6;
    private volatile java.lang.Object curso_;
    /**
     * <code>string curso = 6;</code>
     * @return The curso.
     */
    public java.lang.String getCurso() {
      java.lang.Object ref = curso_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        curso_ = s;
        return s;
      }
    }
    /**
     * <code>string curso = 6;</code>
     * @return The bytes for curso.
     */
    public com.google.protobuf.ByteString
        getCursoBytes() {
      java.lang.Object ref = curso_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        curso_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nome_);
      }
      if (!getUsuarioBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, usuario_);
      }
      if (!getSenhaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, senha_);
      }
      if (!getCpfBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, cpf_);
      }
      if (!getMatriculaBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, matricula_);
      }
      if (!getCursoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, curso_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nome_);
      }
      if (!getUsuarioBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, usuario_);
      }
      if (!getSenhaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, senha_);
      }
      if (!getCpfBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, cpf_);
      }
      if (!getMatriculaBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, matricula_);
      }
      if (!getCursoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, curso_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario)) {
        return super.equals(obj);
      }
      sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario other = (sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario) obj;

      if (!getNome()
          .equals(other.getNome())) return false;
      if (!getUsuario()
          .equals(other.getUsuario())) return false;
      if (!getSenha()
          .equals(other.getSenha())) return false;
      if (!getCpf()
          .equals(other.getCpf())) return false;
      if (!getMatricula()
          .equals(other.getMatricula())) return false;
      if (!getCurso()
          .equals(other.getCurso())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (37 * hash) + USUARIO_FIELD_NUMBER;
      hash = (53 * hash) + getUsuario().hashCode();
      hash = (37 * hash) + SENHA_FIELD_NUMBER;
      hash = (53 * hash) + getSenha().hashCode();
      hash = (37 * hash) + CPF_FIELD_NUMBER;
      hash = (53 * hash) + getCpf().hashCode();
      hash = (37 * hash) + MATRICULA_FIELD_NUMBER;
      hash = (53 * hash) + getMatricula().hashCode();
      hash = (37 * hash) + CURSO_FIELD_NUMBER;
      hash = (53 * hash) + getCurso().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.CadastroUsuario}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.CadastroUsuario)
        sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuarioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sd.ufc.reserva.model.ObjectCadastroUsuario.internal_static_proto_CadastroUsuario_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sd.ufc.reserva.model.ObjectCadastroUsuario.internal_static_proto_CadastroUsuario_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.class, sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.Builder.class);
      }

      // Construct using sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nome_ = "";

        usuario_ = "";

        senha_ = "";

        cpf_ = "";

        matricula_ = "";

        curso_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sd.ufc.reserva.model.ObjectCadastroUsuario.internal_static_proto_CadastroUsuario_descriptor;
      }

      @java.lang.Override
      public sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario getDefaultInstanceForType() {
        return sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.getDefaultInstance();
      }

      @java.lang.Override
      public sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario build() {
        sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario buildPartial() {
        sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario result = new sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario(this);
        result.nome_ = nome_;
        result.usuario_ = usuario_;
        result.senha_ = senha_;
        result.cpf_ = cpf_;
        result.matricula_ = matricula_;
        result.curso_ = curso_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario) {
          return mergeFrom((sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario other) {
        if (other == sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario.getDefaultInstance()) return this;
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        if (!other.getUsuario().isEmpty()) {
          usuario_ = other.usuario_;
          onChanged();
        }
        if (!other.getSenha().isEmpty()) {
          senha_ = other.senha_;
          onChanged();
        }
        if (!other.getCpf().isEmpty()) {
          cpf_ = other.cpf_;
          onChanged();
        }
        if (!other.getMatricula().isEmpty()) {
          matricula_ = other.matricula_;
          onChanged();
        }
        if (!other.getCurso().isEmpty()) {
          curso_ = other.curso_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 1;</code>
       * @return The nome.
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @return The bytes for nome.
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The nome to set.
       * @return This builder for chaining.
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 1;</code>
       * @param value The bytes for nome to set.
       * @return This builder for chaining.
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object usuario_ = "";
      /**
       * <code>string usuario = 2;</code>
       * @return The usuario.
       */
      public java.lang.String getUsuario() {
        java.lang.Object ref = usuario_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          usuario_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string usuario = 2;</code>
       * @return The bytes for usuario.
       */
      public com.google.protobuf.ByteString
          getUsuarioBytes() {
        java.lang.Object ref = usuario_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          usuario_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string usuario = 2;</code>
       * @param value The usuario to set.
       * @return This builder for chaining.
       */
      public Builder setUsuario(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        usuario_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string usuario = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsuario() {
        
        usuario_ = getDefaultInstance().getUsuario();
        onChanged();
        return this;
      }
      /**
       * <code>string usuario = 2;</code>
       * @param value The bytes for usuario to set.
       * @return This builder for chaining.
       */
      public Builder setUsuarioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        usuario_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object senha_ = "";
      /**
       * <code>string senha = 3;</code>
       * @return The senha.
       */
      public java.lang.String getSenha() {
        java.lang.Object ref = senha_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          senha_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string senha = 3;</code>
       * @return The bytes for senha.
       */
      public com.google.protobuf.ByteString
          getSenhaBytes() {
        java.lang.Object ref = senha_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senha_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string senha = 3;</code>
       * @param value The senha to set.
       * @return This builder for chaining.
       */
      public Builder setSenha(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        senha_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string senha = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSenha() {
        
        senha_ = getDefaultInstance().getSenha();
        onChanged();
        return this;
      }
      /**
       * <code>string senha = 3;</code>
       * @param value The bytes for senha to set.
       * @return This builder for chaining.
       */
      public Builder setSenhaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        senha_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object cpf_ = "";
      /**
       * <code>string cpf = 4;</code>
       * @return The cpf.
       */
      public java.lang.String getCpf() {
        java.lang.Object ref = cpf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cpf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cpf = 4;</code>
       * @return The bytes for cpf.
       */
      public com.google.protobuf.ByteString
          getCpfBytes() {
        java.lang.Object ref = cpf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cpf = 4;</code>
       * @param value The cpf to set.
       * @return This builder for chaining.
       */
      public Builder setCpf(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        cpf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string cpf = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpf() {
        
        cpf_ = getDefaultInstance().getCpf();
        onChanged();
        return this;
      }
      /**
       * <code>string cpf = 4;</code>
       * @param value The bytes for cpf to set.
       * @return This builder for chaining.
       */
      public Builder setCpfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        cpf_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object matricula_ = "";
      /**
       * <code>string matricula = 5;</code>
       * @return The matricula.
       */
      public java.lang.String getMatricula() {
        java.lang.Object ref = matricula_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          matricula_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string matricula = 5;</code>
       * @return The bytes for matricula.
       */
      public com.google.protobuf.ByteString
          getMatriculaBytes() {
        java.lang.Object ref = matricula_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          matricula_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string matricula = 5;</code>
       * @param value The matricula to set.
       * @return This builder for chaining.
       */
      public Builder setMatricula(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        matricula_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string matricula = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearMatricula() {
        
        matricula_ = getDefaultInstance().getMatricula();
        onChanged();
        return this;
      }
      /**
       * <code>string matricula = 5;</code>
       * @param value The bytes for matricula to set.
       * @return This builder for chaining.
       */
      public Builder setMatriculaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        matricula_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object curso_ = "";
      /**
       * <code>string curso = 6;</code>
       * @return The curso.
       */
      public java.lang.String getCurso() {
        java.lang.Object ref = curso_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          curso_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string curso = 6;</code>
       * @return The bytes for curso.
       */
      public com.google.protobuf.ByteString
          getCursoBytes() {
        java.lang.Object ref = curso_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          curso_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string curso = 6;</code>
       * @param value The curso to set.
       * @return This builder for chaining.
       */
      public Builder setCurso(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        curso_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string curso = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurso() {
        
        curso_ = getDefaultInstance().getCurso();
        onChanged();
        return this;
      }
      /**
       * <code>string curso = 6;</code>
       * @param value The bytes for curso to set.
       * @return This builder for chaining.
       */
      public Builder setCursoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        curso_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.CadastroUsuario)
    }

    // @@protoc_insertion_point(class_scope:proto.CadastroUsuario)
    private static final sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario();
    }

    public static sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CadastroUsuario>
        PARSER = new com.google.protobuf.AbstractParser<CadastroUsuario>() {
      @java.lang.Override
      public CadastroUsuario parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CadastroUsuario(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CadastroUsuario> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CadastroUsuario> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sd.ufc.reserva.model.ObjectCadastroUsuario.CadastroUsuario getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CadastroUsuario_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CadastroUsuario_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033proto/CadastroUsuario.proto\022\005proto\"n\n\017" +
      "CadastroUsuario\022\014\n\004nome\030\001 \001(\t\022\017\n\007usuario" +
      "\030\002 \001(\t\022\r\n\005senha\030\003 \001(\t\022\013\n\003cpf\030\004 \001(\t\022\021\n\tma" +
      "tricula\030\005 \001(\t\022\r\n\005curso\030\006 \001(\tB-\n\024sd.ufc.r" +
      "eserva.modelB\025ObjectCadastroUsuariob\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_CadastroUsuario_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_CadastroUsuario_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CadastroUsuario_descriptor,
        new java.lang.String[] { "Nome", "Usuario", "Senha", "Cpf", "Matricula", "Curso", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
