// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Reserva.proto

package sd.ufc.reserva.model;

public final class ObjectReserva {
  private ObjectReserva() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ReservaOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Reserva)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 id_usuario = 2;</code>
     * @return The idUsuario.
     */
    int getIdUsuario();

    /**
     * <code>int32 id_sala = 3;</code>
     * @return The idSala.
     */
    int getIdSala();

    /**
     * <code>string data = 4;</code>
     * @return The data.
     */
    java.lang.String getData();
    /**
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();

    /**
     * <code>string horario = 5;</code>
     * @return The horario.
     */
    java.lang.String getHorario();
    /**
     * <code>string horario = 5;</code>
     * @return The bytes for horario.
     */
    com.google.protobuf.ByteString
        getHorarioBytes();
  }
  /**
   * Protobuf type {@code proto.Reserva}
   */
  public  static final class Reserva extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Reserva)
      ReservaOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Reserva.newBuilder() to construct.
    private Reserva(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Reserva() {
      data_ = "";
      horario_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Reserva();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Reserva(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {

              idUsuario_ = input.readInt32();
              break;
            }
            case 24: {

              idSala_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              horario_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return sd.ufc.reserva.model.ObjectReserva.internal_static_proto_Reserva_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return sd.ufc.reserva.model.ObjectReserva.internal_static_proto_Reserva_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              sd.ufc.reserva.model.ObjectReserva.Reserva.class, sd.ufc.reserva.model.ObjectReserva.Reserva.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    public int getId() {
      return id_;
    }

    public static final int ID_USUARIO_FIELD_NUMBER = 2;
    private int idUsuario_;
    /**
     * <code>int32 id_usuario = 2;</code>
     * @return The idUsuario.
     */
    public int getIdUsuario() {
      return idUsuario_;
    }

    public static final int ID_SALA_FIELD_NUMBER = 3;
    private int idSala_;
    /**
     * <code>int32 id_sala = 3;</code>
     * @return The idSala.
     */
    public int getIdSala() {
      return idSala_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private volatile java.lang.Object data_;
    /**
     * <code>string data = 4;</code>
     * @return The data.
     */
    public java.lang.String getData() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 4;</code>
     * @return The bytes for data.
     */
    public com.google.protobuf.ByteString
        getDataBytes() {
      java.lang.Object ref = data_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HORARIO_FIELD_NUMBER = 5;
    private volatile java.lang.Object horario_;
    /**
     * <code>string horario = 5;</code>
     * @return The horario.
     */
    public java.lang.String getHorario() {
      java.lang.Object ref = horario_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        horario_ = s;
        return s;
      }
    }
    /**
     * <code>string horario = 5;</code>
     * @return The bytes for horario.
     */
    public com.google.protobuf.ByteString
        getHorarioBytes() {
      java.lang.Object ref = horario_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        horario_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (idUsuario_ != 0) {
        output.writeInt32(2, idUsuario_);
      }
      if (idSala_ != 0) {
        output.writeInt32(3, idSala_);
      }
      if (!getDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, data_);
      }
      if (!getHorarioBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, horario_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (idUsuario_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, idUsuario_);
      }
      if (idSala_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, idSala_);
      }
      if (!getDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, data_);
      }
      if (!getHorarioBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, horario_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof sd.ufc.reserva.model.ObjectReserva.Reserva)) {
        return super.equals(obj);
      }
      sd.ufc.reserva.model.ObjectReserva.Reserva other = (sd.ufc.reserva.model.ObjectReserva.Reserva) obj;

      if (getId()
          != other.getId()) return false;
      if (getIdUsuario()
          != other.getIdUsuario()) return false;
      if (getIdSala()
          != other.getIdSala()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getHorario()
          .equals(other.getHorario())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ID_USUARIO_FIELD_NUMBER;
      hash = (53 * hash) + getIdUsuario();
      hash = (37 * hash) + ID_SALA_FIELD_NUMBER;
      hash = (53 * hash) + getIdSala();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (37 * hash) + HORARIO_FIELD_NUMBER;
      hash = (53 * hash) + getHorario().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static sd.ufc.reserva.model.ObjectReserva.Reserva parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(sd.ufc.reserva.model.ObjectReserva.Reserva prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Reserva}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Reserva)
        sd.ufc.reserva.model.ObjectReserva.ReservaOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return sd.ufc.reserva.model.ObjectReserva.internal_static_proto_Reserva_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return sd.ufc.reserva.model.ObjectReserva.internal_static_proto_Reserva_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                sd.ufc.reserva.model.ObjectReserva.Reserva.class, sd.ufc.reserva.model.ObjectReserva.Reserva.Builder.class);
      }

      // Construct using sd.ufc.reserva.model.ObjectReserva.Reserva.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        idUsuario_ = 0;

        idSala_ = 0;

        data_ = "";

        horario_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return sd.ufc.reserva.model.ObjectReserva.internal_static_proto_Reserva_descriptor;
      }

      @java.lang.Override
      public sd.ufc.reserva.model.ObjectReserva.Reserva getDefaultInstanceForType() {
        return sd.ufc.reserva.model.ObjectReserva.Reserva.getDefaultInstance();
      }

      @java.lang.Override
      public sd.ufc.reserva.model.ObjectReserva.Reserva build() {
        sd.ufc.reserva.model.ObjectReserva.Reserva result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public sd.ufc.reserva.model.ObjectReserva.Reserva buildPartial() {
        sd.ufc.reserva.model.ObjectReserva.Reserva result = new sd.ufc.reserva.model.ObjectReserva.Reserva(this);
        result.id_ = id_;
        result.idUsuario_ = idUsuario_;
        result.idSala_ = idSala_;
        result.data_ = data_;
        result.horario_ = horario_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof sd.ufc.reserva.model.ObjectReserva.Reserva) {
          return mergeFrom((sd.ufc.reserva.model.ObjectReserva.Reserva)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(sd.ufc.reserva.model.ObjectReserva.Reserva other) {
        if (other == sd.ufc.reserva.model.ObjectReserva.Reserva.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getIdUsuario() != 0) {
          setIdUsuario(other.getIdUsuario());
        }
        if (other.getIdSala() != 0) {
          setIdSala(other.getIdSala());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        if (!other.getHorario().isEmpty()) {
          horario_ = other.horario_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        sd.ufc.reserva.model.ObjectReserva.Reserva parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (sd.ufc.reserva.model.ObjectReserva.Reserva) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int idUsuario_ ;
      /**
       * <code>int32 id_usuario = 2;</code>
       * @return The idUsuario.
       */
      public int getIdUsuario() {
        return idUsuario_;
      }
      /**
       * <code>int32 id_usuario = 2;</code>
       * @param value The idUsuario to set.
       * @return This builder for chaining.
       */
      public Builder setIdUsuario(int value) {
        
        idUsuario_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id_usuario = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdUsuario() {
        
        idUsuario_ = 0;
        onChanged();
        return this;
      }

      private int idSala_ ;
      /**
       * <code>int32 id_sala = 3;</code>
       * @return The idSala.
       */
      public int getIdSala() {
        return idSala_;
      }
      /**
       * <code>int32 id_sala = 3;</code>
       * @param value The idSala to set.
       * @return This builder for chaining.
       */
      public Builder setIdSala(int value) {
        
        idSala_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id_sala = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdSala() {
        
        idSala_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object data_ = "";
      /**
       * <code>string data = 4;</code>
       * @return The data.
       */
      public java.lang.String getData() {
        java.lang.Object ref = data_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string data = 4;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        java.lang.Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 4;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object horario_ = "";
      /**
       * <code>string horario = 5;</code>
       * @return The horario.
       */
      public java.lang.String getHorario() {
        java.lang.Object ref = horario_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          horario_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string horario = 5;</code>
       * @return The bytes for horario.
       */
      public com.google.protobuf.ByteString
          getHorarioBytes() {
        java.lang.Object ref = horario_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          horario_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string horario = 5;</code>
       * @param value The horario to set.
       * @return This builder for chaining.
       */
      public Builder setHorario(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        horario_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string horario = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHorario() {
        
        horario_ = getDefaultInstance().getHorario();
        onChanged();
        return this;
      }
      /**
       * <code>string horario = 5;</code>
       * @param value The bytes for horario to set.
       * @return This builder for chaining.
       */
      public Builder setHorarioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        horario_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Reserva)
    }

    // @@protoc_insertion_point(class_scope:proto.Reserva)
    private static final sd.ufc.reserva.model.ObjectReserva.Reserva DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new sd.ufc.reserva.model.ObjectReserva.Reserva();
    }

    public static sd.ufc.reserva.model.ObjectReserva.Reserva getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Reserva>
        PARSER = new com.google.protobuf.AbstractParser<Reserva>() {
      @java.lang.Override
      public Reserva parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Reserva(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Reserva> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Reserva> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public sd.ufc.reserva.model.ObjectReserva.Reserva getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Reserva_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Reserva_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rReserva.proto\022\005proto\"Y\n\007Reserva\022\n\n\002id\030" +
      "\001 \001(\005\022\022\n\nid_usuario\030\002 \001(\005\022\017\n\007id_sala\030\003 \001" +
      "(\005\022\014\n\004data\030\004 \001(\t\022\017\n\007horario\030\005 \001(\tB%\n\024sd." +
      "ufc.reserva.modelB\rObjectReservab\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Reserva_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Reserva_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Reserva_descriptor,
        new java.lang.String[] { "Id", "IdUsuario", "IdSala", "Data", "Horario", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
